"""Added items model

Revision ID: 2e8680b7da46
Revises: 3463908b8b5c
Create Date: 2016-08-21 17:09:24.937166

"""

# revision identifiers, used by Alembic.
revision = '2e8680b7da46'
down_revision = '3463908b8b5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sn', sa.String(length=24), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('sn')
    )
    op.create_index('ix_items_timestamp', 'items', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_timestamp', 'items')
    op.drop_table('items')
    ### end Alembic commands ###
