"""empty message

Revision ID: 319eb76166a
Revises: 563ff2c88733
Create Date: 2016-09-07 20:09:59.433646

"""

# revision identifiers, used by Alembic.
revision = '319eb76166a'
down_revision = '563ff2c88733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stocktakes_start_date', 'stocktakes', ['start_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocktakes_start_date', 'stocktakes')
    op.drop_table('stocktakes')
    ### end Alembic commands ###
