"""added table for sotcktake items

Revision ID: 3365964e96fd
Revises: 4022e98e8e39
Create Date: 2016-09-08 19:49:43.437274

"""

# revision identifiers, used by Alembic.
revision = '3365964e96fd'
down_revision = '4022e98e8e39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=24), nullable=True),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sn', sa.String(length=24), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), nullable=True),
    sa.Column('stocktake', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stocktake'], ['stocktakes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('sn')
    )
    op.create_index('ix_stitems_timestamp', 'stitems', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stitems_timestamp', 'stitems')
    op.drop_table('stitems')
    ### end Alembic commands ###
