"""Added confrim column to User model

Revision ID: 467b6c542e5f
Revises: 35a20b337d32
Create Date: 2016-08-16 21:50:54.709152

"""

# revision identifiers, used by Alembic.
revision = '467b6c542e5f'
down_revision = '35a20b337d32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
