"""fixed item migration

Revision ID: 5397830926a
Revises: 2e8680b7da46
Create Date: 2016-08-21 18:02:10.698687

"""

# revision identifiers, used by Alembic.
revision = '5397830926a'
down_revision = '2e8680b7da46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
