"""init migrate

Revision ID: 563ff2c88733
Revises: None
Create Date: 2016-09-02 20:12:53.522293

"""

# revision identifiers, used by Alembic.
revision = '563ff2c88733'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
