"""Initial migration

Revision ID: 56a911a20d27
Revises: None
Create Date: 2016-08-03 20:17:22.324117

"""

# revision identifiers, used by Alembic.
revision = '56a911a20d27'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
