"""fixed stitems model - no unique values

Revision ID: d70dac39236
Revises: 3365964e96fd
Create Date: 2016-09-08 20:15:40.232541

"""

# revision identifiers, used by Alembic.
revision = 'd70dac39236'
down_revision = '3365964e96fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stitems_timestamp', 'stitems')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stitems_timestamp', 'stitems', ['timestamp'], unique=False)
    ### end Alembic commands ###
